# Permalinks
#
permalink:           /posts/:title/

# Setup
title:               Kir Shatrov
tagline:             ''
description:         'Personal website by Kir Shatrov'
url:                 http://kirshatrov.com
baseurl:             ''

exclude: [vendor]
markdown: kramdown
highlighter: rouge

# About/contact
author:
  name:              Kir Shatrov
  url:               http://kirshatrov.com
  email:             kir@kirshatrov.com
  twitter:           kirshatrov
# Custom vars
version:             1.0.0
disqus: true
disqus_shortname: 'iempire-blog'

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

include: ['pages']
