# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Kir Shatrov blog
tagline:             ''
description:         'My personal blog, mostly about technical staff.'
url:                 http://blog.iempire.ru
baseurl:             ''
paginate:            5

exclude: [vendor]

# About/contact
author:
  name:              Kir Shatrov
  url:               https://iempire.ru
  email:             shatrov@me.com
  twitter:           kirshatrov
# Custom vars
version:             1.0.0
disqus: true
disqus_shortname: 'iempire-blog'
