# Permalinks
#
permalink:           pretty

# Setup
title:               Kir Shatrov blog
tagline:             ''
description:         'My personal blog, mostly about technical staff.'
url:                 http://blog.iempire.ru
baseurl:             ''
paginate:            8

exclude: [vendor]
markdown: kramdown
highlighter: rouge

# About/contact
author:
  name:              Kir Shatrov
  url:               https://iempire.ru
  email:             shatrov@me.com
  twitter:           kirshatrov
# Custom vars
version:             1.0.0
disqus: true
disqus_shortname: 'iempire-blog'

gems:
  - jekyll-sitemap
  - jekyll-paginate
