# Permalinks
#
permalink:           pretty

# Setup
title:               Kir Shatrov
tagline:             ''
description:         'My personal blog, mostly about technical staff.'
url:                 http://kirshatrov.com
baseurl:             ''
paginate:            8
paginate_path:       "/posts/page:num/"

exclude: [vendor]
markdown: kramdown
highlighter: rouge

# About/contact
author:
  name:              Kir Shatrov
  url:               http://kirshatrov.com
  email:             kir@kirshatrov.com
  twitter:           kirshatrov
# Custom vars
version:             1.0.0
disqus: true
disqus_shortname: 'iempire-blog'

gems:
  - jekyll-sitemap
  - jekyll-paginate

include: ['pages']
